//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TermProject.ServiceReference3 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference3.SellerTestSoap")]
    public interface SellerTestSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NotifyBuyer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet NotifyBuyer(string buyer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NotifyBuyer", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> NotifyBuyerAsync(string buyer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AcceptOffer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int AcceptOffer(string house);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AcceptOffer", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AcceptOfferAsync(string house);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNewOffers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetNewOffers(string sellerUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNewOffers", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetNewOffersAsync(string sellerUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNewShowings", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetNewShowings(string sellerUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNewShowings", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetNewShowingsAsync(string sellerUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSellerInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetSellerInfo(string sellerUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSellerInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetSellerInfoAsync(string sellerUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSurvery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetSurvery(string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSurvery", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetSurveryAsync(string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRooms", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetRooms(string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRooms", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetRoomsAsync(string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetHouse", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetHouse(string realestate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetHouse", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetHouseAsync(string realestate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetHousePrice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetHousePrice(string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetHousePrice", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetHousePriceAsync(string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetShowings", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetShowings(string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetShowings", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetShowingsAsync(string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOffers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetOffers(string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOffers", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetOffersAsync(string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateHouse", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int UpdateHouse(string address, string description, string status, string photo, int price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateHouse", ReplyAction="*")]
        System.Threading.Tasks.Task<int> UpdateHouseAsync(string address, string description, string status, string photo, int price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteHouse", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int DeleteHouse(string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteHouse", ReplyAction="*")]
        System.Threading.Tasks.Task<int> DeleteHouseAsync(string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetComments", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetComments(string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetComments", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetCommentsAsync(string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SellerTestSoapChannel : TermProject.ServiceReference3.SellerTestSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SellerTestSoapClient : System.ServiceModel.ClientBase<TermProject.ServiceReference3.SellerTestSoap>, TermProject.ServiceReference3.SellerTestSoap {
        
        public SellerTestSoapClient() {
        }
        
        public SellerTestSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SellerTestSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SellerTestSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SellerTestSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet NotifyBuyer(string buyer) {
            return base.Channel.NotifyBuyer(buyer);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> NotifyBuyerAsync(string buyer) {
            return base.Channel.NotifyBuyerAsync(buyer);
        }
        
        public int AcceptOffer(string house) {
            return base.Channel.AcceptOffer(house);
        }
        
        public System.Threading.Tasks.Task<int> AcceptOfferAsync(string house) {
            return base.Channel.AcceptOfferAsync(house);
        }
        
        public System.Data.DataSet GetNewOffers(string sellerUsername) {
            return base.Channel.GetNewOffers(sellerUsername);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetNewOffersAsync(string sellerUsername) {
            return base.Channel.GetNewOffersAsync(sellerUsername);
        }
        
        public System.Data.DataSet GetNewShowings(string sellerUsername) {
            return base.Channel.GetNewShowings(sellerUsername);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetNewShowingsAsync(string sellerUsername) {
            return base.Channel.GetNewShowingsAsync(sellerUsername);
        }
        
        public System.Data.DataSet GetSellerInfo(string sellerUsername) {
            return base.Channel.GetSellerInfo(sellerUsername);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetSellerInfoAsync(string sellerUsername) {
            return base.Channel.GetSellerInfoAsync(sellerUsername);
        }
        
        public System.Data.DataSet GetSurvery(string address) {
            return base.Channel.GetSurvery(address);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetSurveryAsync(string address) {
            return base.Channel.GetSurveryAsync(address);
        }
        
        public System.Data.DataSet GetRooms(string address) {
            return base.Channel.GetRooms(address);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetRoomsAsync(string address) {
            return base.Channel.GetRoomsAsync(address);
        }
        
        public System.Data.DataSet GetHouse(string realestate) {
            return base.Channel.GetHouse(realestate);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetHouseAsync(string realestate) {
            return base.Channel.GetHouseAsync(realestate);
        }
        
        public System.Data.DataSet GetHousePrice(string address) {
            return base.Channel.GetHousePrice(address);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetHousePriceAsync(string address) {
            return base.Channel.GetHousePriceAsync(address);
        }
        
        public System.Data.DataSet GetShowings(string address) {
            return base.Channel.GetShowings(address);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetShowingsAsync(string address) {
            return base.Channel.GetShowingsAsync(address);
        }
        
        public System.Data.DataSet GetOffers(string address) {
            return base.Channel.GetOffers(address);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetOffersAsync(string address) {
            return base.Channel.GetOffersAsync(address);
        }
        
        public int UpdateHouse(string address, string description, string status, string photo, int price) {
            return base.Channel.UpdateHouse(address, description, status, photo, price);
        }
        
        public System.Threading.Tasks.Task<int> UpdateHouseAsync(string address, string description, string status, string photo, int price) {
            return base.Channel.UpdateHouseAsync(address, description, status, photo, price);
        }
        
        public int DeleteHouse(string address) {
            return base.Channel.DeleteHouse(address);
        }
        
        public System.Threading.Tasks.Task<int> DeleteHouseAsync(string address) {
            return base.Channel.DeleteHouseAsync(address);
        }
        
        public System.Data.DataSet GetComments(string address) {
            return base.Channel.GetComments(address);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetCommentsAsync(string address) {
            return base.Channel.GetCommentsAsync(address);
        }
        
        public string HelloWorld(string name) {
            return base.Channel.HelloWorld(name);
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync(string name) {
            return base.Channel.HelloWorldAsync(name);
        }
    }
}
